# Networkit core
include "cython/Import.pyx"
include "cython/Global.pyx"
include "cython/Auxiliary.pyx"
include "cython/Graph.pyx"
include "cython/Dynamics.pyx"

# NetworKit algorithms
include "cython/Coarsening.pyx"
include "cython/Linkprediction.pyx"
include "cython/Scd.pyx"
include "cython/Centrality.pyx"
include "cython/Community.pyx"
include "cython/Edgescore.pyx"
include "cython/Matching.pyx"
include "cython/Sparsification.pyx"
include "cython/Clique.pyx"
include "cython/Components.pyx"
include "cython/Flow.pyx"
include "cython/Graphio.pyx"
include "cython/Misc.pyx"
include "cython/Structures.pyx"
include "cython/ClusteringCoef.pyx"
include "cython/Distance.pyx"
include "cython/Generators.pyx"
include "cython/Independentset.pyx"
include "cython/Profiling.pyx"
include "cython/Viz.pyx"
